server {
    listen 80;
    server_name 161.118.168.179;
    root /home/ubuntu/dcoderguy-main;  # adjust path after git clone on VPS
    index index.html;
    location / {
        try_files $uri $uri/ =404;
    }
    location /admin {
        try_files /admin.html =404;
    }
}
